import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { S3Client } from '@aws-sdk/client-s3';
import { env } from '../config/env';
import { logger } from './logger';

/**
 * Where uploaded files live.
 *
 * One interface, two implementations, so development needs no object store and
 * production needs no shared disk. The same code path runs in both, which is
 * what stops storage bugs appearing only after deployment.
 */
export interface StoredObject {
  key: string;
  sizeBytes: number;
  checksum: string;
}

export interface StorageAdapter {
  put(buffer: Buffer, options: { contentType: string; fileName: string }): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

/** Keys are generated, never taken from the file name, so a name cannot escape. */
function newKey(fileName: string): string {
  const safeExtension = /\.([A-Za-z0-9]{1,8})$/.exec(fileName)?.[1]?.toLowerCase() ?? 'bin';
  const now = new Date();
  return (
    now.getUTCFullYear() +
    '/' +
    String(now.getUTCMonth() + 1).padStart(2, '0') +
    '/' +
    randomUUID() +
    '.' +
    safeExtension
  );
}

class LocalDiskAdapter implements StorageAdapter {
  private readonly root = resolve(env.STORAGE_LOCAL_DIR);

  private pathFor(key: string): string {
    const full = resolve(this.root, key);
    // A key is generated by us, but resolve it anyway: a stored key that
    // escaped the root would be a path traversal waiting to be read back.
    if (!full.startsWith(this.root)) throw new Error('Refusing a storage key outside the root');
    return full;
  }

  async put(buffer: Buffer, options: { contentType: string; fileName: string }) {
    const key = newKey(options.fileName);
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buffer);
    return {
      key,
      sizeBytes: buffer.byteLength,
      checksum: createHash('sha256').update(buffer).digest('hex'),
    };
  }

  async get(key: string) {
    return readFile(this.pathFor(key));
  }

  async remove(key: string) {
    await unlink(this.pathFor(key)).catch(() => {
      // Already gone is the outcome we wanted.
    });
  }
}

class S3Adapter implements StorageAdapter {
  private client: S3Client | null = null;

  private async getClient() {
    if (this.client) return this.client;
    const { S3Client } = await import('@aws-sdk/client-s3');
    this.client = new S3Client({
      region: env.S3_REGION,
      ...(env.S3_ENDPOINT ? { endpoint: env.S3_ENDPOINT } : {}),
      forcePathStyle: env.S3_FORCE_PATH_STYLE,
      ...(env.S3_ACCESS_KEY_ID && env.S3_SECRET_ACCESS_KEY
        ? {
            credentials: {
              accessKeyId: env.S3_ACCESS_KEY_ID,
              secretAccessKey: env.S3_SECRET_ACCESS_KEY,
            },
          }
        : {}),
    });
    return this.client;
  }

  async put(buffer: Buffer, options: { contentType: string; fileName: string }) {
    const { PutObjectCommand } = await import('@aws-sdk/client-s3');
    const client = await this.getClient();
    const key = newKey(options.fileName);

    await client.send(
      new PutObjectCommand({
        Bucket: env.S3_BUCKET,
        Key: key,
        Body: buffer,
        ContentType: options.contentType,
        // Stops a browser being talked into rendering an upload as a page.
        ContentDisposition: 'attachment',
      }),
    );

    return {
      key,
      sizeBytes: buffer.byteLength,
      checksum: createHash('sha256').update(buffer).digest('hex'),
    };
  }

  async get(key: string) {
    const { GetObjectCommand } = await import('@aws-sdk/client-s3');
    const client = await this.getClient();
    const response = await client.send(
      new GetObjectCommand({ Bucket: env.S3_BUCKET, Key: key }),
    );
    const chunks: Buffer[] = [];
    for await (const chunk of response.Body as AsyncIterable<Uint8Array>) {
      chunks.push(Buffer.from(chunk));
    }
    return Buffer.concat(chunks);
  }

  async remove(key: string) {
    const { DeleteObjectCommand } = await import('@aws-sdk/client-s3');
    const client = await this.getClient();
    await client.send(new DeleteObjectCommand({ Bucket: env.S3_BUCKET, Key: key }));
  }
}

let adapter: StorageAdapter | null = null;

export function getStorage(): StorageAdapter {
  if (!adapter) {
    adapter = env.STORAGE_DRIVER === 's3' ? new S3Adapter() : new LocalDiskAdapter();
    logger.info({ driver: env.STORAGE_DRIVER }, 'Storage ready.');
  }
  return adapter;
}

export { join };
